title: Robot antenna Scratch 2
hero_image: images/banner.png
description: Control a robot's antenna light with a Raspberry Pi and code blocks
listed: false
copyedit: true
version: 4.1.0
last_tested: 2018-01-17
steps: 
- title: Introduction
- title: Make an antenna
- title: Connect your antenna
- title: Make the antenna flash with code
- title: Make a cardboard robot
- title: "Challenge: beeps and flashes"
  challenge: true
- title: What next?